spring.application.name=starlight-gateway
server.port=8080

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# USER SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://STARLIGHT-USER
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

# =========================
# ROOM SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[1].id=room-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://STARLIGHT-ROOM
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/rooms/**

# =========================
# BOOKING SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[2].id=booking-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://STARLIGHT-BOOKING
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/bookings/**